### ISSUE TITLE
Resolver TODO: Contatos Empresariais na Etapa Mediana

### ISSUE THREAD

**Issue by JPTIZ** [seccom-ufsc/manual#10]
Resolver TODO em um arquivo existente
-------------------------------------

- **Arquivo**: [3. Etapa Mediana](https://github.com/seccom-ufsc/manual/wiki/3.-Etapa-Mediana#2---troca-de-e-mails-empresas)

- **Local**: "2 - Troca de E-mails Empresas"

- **O que fazer**: Está totalmente em branco, então, use sua criatividade.

**Comment by Thaleszh** [comment]
Feito
